/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/components/super-tab';
import * as i2 from '../../../src/components/super-tabs';
import * as i3 from 'ionic-angular/components/app/app';
import * as i4 from 'ionic-angular/config/config';
import * as i5 from 'ionic-angular/platform/platform';
import * as i6 from 'ionic-angular/gestures/gesture-controller';
import * as i7 from 'ionic-angular/transitions/transition-controller';
import * as i8 from 'ionic-angular/navigation/deep-linker';
import * as i9 from 'ionic-angular/platform/dom-controller';
const styles_SuperTab:any[] = ([] as any[]);
export const RenderType_SuperTab:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_SuperTab,
    data:{}});
export function View_SuperTab_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{_vp:0}),(_l()(),i0.ɵeld(16777216,[[1,3],['viewport',
      1]],(null as any),0,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵeld(0,(null as any),(null as any),
      0,'div',[['class','nav-decor']],(null as any),(null as any),(null as any),(null as any),
      (null as any)))],(null as any),(null as any));
}
export function View_SuperTab_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'super-tab',([] as any[]),
      (null as any),(null as any),(null as any),View_SuperTab_0,RenderType_SuperTab)),
      i0.ɵdid(4440064,(null as any),0,i1.SuperTab,[i2.SuperTabs,i3.App,i4.Config,i5.Platform,
          i0.ElementRef,i0.NgZone,i0.Renderer,i0.ComponentFactoryResolver,i6.GestureController,
          i7.TransitionController,i0.ErrorHandler,[2,i8.DeepLinker],i9.DomController,
          i0.ChangeDetectorRef],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SuperTabNgFactory:i0.ComponentFactory<i1.SuperTab> = i0.ɵccf('super-tab',
    i1.SuperTab,View_SuperTab_Host_0,{color:'color',mode:'mode',swipeBackEnabled:'swipeBackEnabled',
        title:'title',icon:'icon',root:'root',rootParams:'rootParams',tabId:'id',badge:'badge'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQnVzc21hbm5JVC9Qcm9qZWt0ZS9Tb25zdGlnZXMvaW9uaWMyLXN1cGVyLXRhYnMvc3JjL2NvbXBvbmVudHMvc3VwZXItdGFiLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0J1c3NtYW5uSVQvUHJvamVrdGUvU29uc3RpZ2VzL2lvbmljMi1zdXBlci10YWJzL3NyYy9jb21wb25lbnRzL3N1cGVyLXRhYi50cyIsIm5nOi8vL0Q6L0J1c3NtYW5uSVQvUHJvamVrdGUvU29uc3RpZ2VzL2lvbmljMi1zdXBlci10YWJzL3NyYy9jb21wb25lbnRzL3N1cGVyLXRhYi50cy5TdXBlclRhYi5odG1sIiwibmc6Ly8vRDovQnVzc21hbm5JVC9Qcm9qZWt0ZS9Tb25zdGlnZXMvaW9uaWMyLXN1cGVyLXRhYnMvc3JjL2NvbXBvbmVudHMvc3VwZXItdGFiLnRzLlN1cGVyVGFiX0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiAjdmlld3BvcnQ+PC9kaXY+PGRpdiBjbGFzcz1cIm5hdi1kZWNvclwiPjwvZGl2PiIsIjxzdXBlci10YWI+PC9zdXBlci10YWI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztpRENBQTtNQUFBO01BQUEsOEJBQXFCO01BQUE7TUFBQTs7O29CQ0FyQjtNQUFBO2FBQUE7O2tEQUFBOzhCQUFBO0lBQUE7Ozs7OzsifQ==
