/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/components/super-tabs-container';
import * as i2 from 'ionic-angular/platform/platform';
const styles_SuperTabsContainer:any[] = ([] as any[]);
export const RenderType_SuperTabsContainer:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_SuperTabsContainer,data:{}});
export function View_SuperTabsContainer_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{container:0}),(_l()(),i0.ɵeld(0,[[1,0],['container',
      1]],(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),i0.ɵncd((null as any),0)],(null as any),(null as any));
}
export function View_SuperTabsContainer_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'super-tabs-container',
      ([] as any[]),(null as any),(null as any),(null as any),View_SuperTabsContainer_0,
      RenderType_SuperTabsContainer)),i0.ɵdid(4374528,(null as any),0,i1.SuperTabsContainer,
      [i0.ElementRef,i0.Renderer2,i2.Platform,i0.NgZone],(null as any),(null as any))],
      (null as any),(null as any));
}
export const SuperTabsContainerNgFactory:i0.ComponentFactory<i1.SuperTabsContainer> = i0.ɵccf('super-tabs-container',
    i1.SuperTabsContainer,View_SuperTabsContainer_Host_0,{config:'config',tabsCount:'tabsCount',
        selectedTabIndex:'selectedTabIndex'},{tabSelect:'tabSelect',onDrag:'onDrag'},
    ['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQnVzc21hbm5JVC9Qcm9qZWt0ZS9Tb25zdGlnZXMvaW9uaWMyLXN1cGVyLXRhYnMvc3JjL2NvbXBvbmVudHMvc3VwZXItdGFicy1jb250YWluZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQnVzc21hbm5JVC9Qcm9qZWt0ZS9Tb25zdGlnZXMvaW9uaWMyLXN1cGVyLXRhYnMvc3JjL2NvbXBvbmVudHMvc3VwZXItdGFicy1jb250YWluZXIudHMiLCJuZzovLy9EOi9CdXNzbWFubklUL1Byb2pla3RlL1NvbnN0aWdlcy9pb25pYzItc3VwZXItdGFicy9zcmMvY29tcG9uZW50cy9zdXBlci10YWJzLWNvbnRhaW5lci50cy5TdXBlclRhYnNDb250YWluZXIuaHRtbCIsIm5nOi8vL0Q6L0J1c3NtYW5uSVQvUHJvamVrdGUvU29uc3RpZ2VzL2lvbmljMi1zdXBlci10YWJzL3NyYy9jb21wb25lbnRzL3N1cGVyLXRhYnMtY29udGFpbmVyLnRzLlN1cGVyVGFic0NvbnRhaW5lcl9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgI2NvbnRhaW5lcj48bmctY29udGVudD48L25nLWNvbnRlbnQ+PC9kaXY+IiwiPHN1cGVyLXRhYnMtY29udGFpbmVyPjwvc3VwZXItdGFicy1jb250YWluZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O3VEQ0FBO01BQUE7TUFBQSxxQ0FBZ0I7OztvQkNBaEI7TUFBQTttQ0FBQSxVQUFBO01BQUE7Ozs7OzsifQ==
